# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='medium',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
